---
# install via `helmfile -f charts/zipkin/ci/helmfile.yaml sync`
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

# Prometheus is too much to configure manually in a test yaml. We need the CRD
# servicemonitors.monitoring.coreos.com as well as Prometheus, deployed as the
# service named "prometheus-operated" in our test namespace "ci-monitoring"
releases:
  - name: prometheus-stack
    namespace: ci-monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    values:
      - prometheusOperator:
          enabled: true
        prometheus:
          enabled: true
          prometheusSpec:
            # Allow any namespace and any values
            serviceMonitorNamespaceSelector:
              any: true
            serviceMonitorSelector:
              any: true
            serviceMonitorSelectorNilUsesHelmValues: false
        # Disable anything else, like multi-container grafana pods.
        defaultRules:
          enabled: false
        alertmanager:
          enabled: false
        kubeApiServer:
          enabled: false
        kubelet:
          enabled: false
        kubeControllerManager:
          enabled: false
        coreDns:
          enabled: false
        kubeDns:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        grafana:
          enabled: false
